Repository gestaltjs/gestalt, pull requests merged in 2022-03, with the labels that each got.

#40 feat: add github templates for issues and PRs.
  .github/issue_template.md
  .github/pull_request_template.md
Labels: enhancement, size/M

#43 Build improvements
  bin/create-app
  bin/gestalt
  packages/gestaltjs/rollup.config.js
Labels: size/S

#45 Set up code coverage with codecov
  .github/workflows/gestalt.yml
  .gitignore
  README.md
  packages/build/package.json
  packages/check/package.json
  packages/core/package.json
  packages/create-app/package.json
  packages/db/package.json
  packages/gestaltjs/package.json
  packages/lint/package.json
  packages/serve/package.json
  packages/test/package.json
  packages/testing/package.json
Labels: size/M

#44 Disable pnpm hoisting
  .npmrc
  package.json
  packages/build/package.json
  packages/check/package.json
  packages/core/package.json
  packages/db/package.json
  packages/docs/package.json
  packages/docs/src/pages/index.js
  packages/lint/package.json
  packages/serve/package.json
  packages/test/package.json
  pnpm-lock.yaml
Labels: size/XXL

#42 Test terminal functions and add an interface to generate hyperlinks
  packages/core/src/cli/index.ts
  packages/core/src/cli/terminal.test.ts
  packages/core/src/cli/terminal.ts
Labels: size/L

#39 @gestaltjs/eslint-plugin-gestaltjs
  .changeset/config.json
  .changeset/giant-lies-sparkle.md
  fixtures/app_with_passing_tests/package.json
  packages/core/rollup.config.js
  packages/core/src/index.test.ts
  packages/eslint-plugin/package.json
  packages/eslint-plugin/rollup.config.js
  packages/eslint-plugin/src/configs/recommended.ts
  packages/eslint-plugin/src/configs/rules/gestalt.ts
  packages/eslint-plugin/src/index.test.ts
  packages/eslint-plugin/src/index.ts
  packages/eslint-plugin/tsconfig.json
  packages/eslint-plugin/vitest.config.ts
  packages/gestaltjs/package.json
  pnpm-lock.yaml
  vitest.config.ts
Labels: size/L

#47 Distribute packages independently
  .changeset/config.json
  configurations/rollup.config.js
  package.json
  packages/build/package.json
  packages/build/rollup.config.js
  packages/build/src/cli/logger.ts
  packages/build/src/cli/logger/transport.ts
  packages/check/package.json
  packages/check/rollup.config.js
  packages/check/src/cli/logger.ts
  packages/check/src/cli/logger/transport.ts
  packages/core/package.json
  packages/core/rollup.config.js
  packages/core/src/cli/logger.ts
  packages/create-app/rollup.config.js
  packages/db/package.json
  packages/db/rollup.config.js
  packages/db/src/cli/logger.ts
  packages/db/src/cli/logger/transport.ts
  packages/docs/package.json
  packages/eslint-plugin/rollup.config.js
  packages/gestaltjs/package.json
  packages/gestaltjs/rollup.config.js
  packages/gestaltjs/src/index.ts
  packages/gestaltjs/src/logger.ts
  packages/lint/package.json
  packages/lint/rollup.config.js
  packages/lint/src/cli/logger.ts
  packages/lint/src/cli/logger/transport.ts
  packages/serve/package.json
  packages/serve/rollup.config.js
  packages/serve/src/cli/logger.ts
  packages/serve/src/cli/logger/transport.ts
  packages/test/package.json
  packages/test/rollup.config.js
  packages/test/src/cli/logger.ts
  packages/test/src/cli/logger/transport.ts
  pnpm-lock.yaml
  tsconfig.base.json
Labels: size/XL

#53 Write a blog post on building a "cohesive app development experience that sparks joy"
  packages/docs/blog/2022-03-14-cohesive-framework/index.md
  packages/docs/blog/2022-03-14-cohesive-framework/rails-vs-others.png
Labels: size/M

#46 Standardize and document throwing and handling of errors across the codebase
  package.json
  packages/build/package.json
  packages/build/src/cli/commands/build.ts
  packages/check/package.json
  packages/core/package.json
  packages/core/src/cli/app.test.ts
  packages/core/src/cli/app.ts
  packages/core/src/cli/error.ts
  packages/core/src/cli/logger.ts
  packages/core/src/cli/logger/transport.ts
  packages/create-app/package.json
  packages/db/package.json
  packages/docs/docs/contributors/errors.md
  packages/docs/sidebars.js
  packages/eslint-plugin/package.json
  packages/gestaltjs/package.json
  packages/gestaltjs/src/index.ts
  packages/serve/package.json
  packages/serve/src/cli/utilities/serve.ts
  packages/test/package.json
  packages/testing/package.json
Labels: size/L

#63 Add packages/core/src/cli/template.ts
  packages/core/package.json
  packages/core/src/cli/fs.ts
  packages/core/src/cli/index.ts
  packages/core/src/cli/template.test.ts
  packages/core/src/cli/template.ts
  packages/testing/package.json
  packages/testing/src/index.ts
  packages/testing/src/temporary.ts
  pnpm-lock.yaml
  vitest.config.ts
Labels: size/L
