Repository gestaltjs/gestalt, pull requests merged in 2022-04, with the labels that each got.

#90 Introduce the concept of renderers
  .changeset/config.json
  configurations/rollup.config.js
  packages/core/package.json
  packages/renderer/package.json
  packages/renderer/rollup.config.js
  packages/renderer/src/index.test.ts
  packages/renderer/src/index.ts
  packages/renderer/src/renderer.ts
  packages/renderer/tsconfig.json
  packages/renderer/vitest.config.ts
  packages/vue-renderer/package.json
  packages/vue-renderer/rollup.config.js
  packages/vue-renderer/src/index.test.ts
  packages/vue-renderer/src/index.ts
  packages/vue-renderer/tsconfig.json
  packages/vue-renderer/vitest.config.ts
  packages/website/docs/.vitepress/config.js
  packages/website/docs/contributors/architecture.md
  packages/website/docs/contributors/renderers.md
  pnpm-lock.yaml
  tsconfig.base.json
Labels: size/L

#95 Fix scaffold awaits
  packages/core/src/cli/fs.ts
  packages/core/src/cli/template.test.ts
  packages/core/src/cli/template.ts
Labels: size/S

#54 Configuration loading and watching
  LICENSE
  packages/build/src/cli/commands/build.ts
  packages/check/src/cli/commands/check.ts
  packages/core/package.json
  packages/core/src/cli/app.ts
  packages/core/src/cli/app/load.test.ts
  packages/core/src/cli/app/load.ts
  packages/core/src/cli/constants.ts
  packages/core/src/cli/environment.ts
  packages/core/src/cli/index.ts
  packages/core/src/cli/project.ts
  packages/core/src/cli/project/load/config.test.ts
  packages/core/src/cli/project/load/config.ts
  packages/core/src/cli/project/load/project.ts
  packages/core/src/cli/project/models/project.ts
  packages/db/src/cli/commands/db/migrate.ts
  packages/dev/src/cli/commands/dev.ts
  packages/dev/src/cli/utilities/dev.ts
  packages/gestaltjs/src/framework/configuration.ts
  packages/test/src/cli/commands/test.ts
  packages/testing/package.json
  packages/testing/src/index.ts
  packages/testing/src/temporary.ts
  packages/testing/src/workspace.ts
  packages/testing/yarn.lock
  packages/website/docs/.vitepress/config.js
  packages/website/docs/reference/configuration/gestalt.md
  pnpm-lock.yaml
  tsconfig.base.json
Labels: size/XXL
